### ISSUE TITLE
FasterR-CNN pretrained model

### ISSUE THREAD

**Issue by sanketsans** [fpv-iplab/stillfast#1]
Hi, 
Just wanted to know why is it that the RPN module is set to be loaded twice. 
As mentioned here, 
https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L15 

The class is inherited from FasterCNN class. Is it correct that when initializing the pretrained config is set to False, and is loaded separetly from StillFast class. 

Besides, I tried to run the model on v2 ego4d. I am afraid I am doing something wrong since the results are very poor. For still images, I extract the image from lmdb database, instead of loading them separately from an extracted image(as followed in code). 

Can you help me here ? 

Thanks :) 
Sanket

**Comment by antoninofurnari** [comment]
Hi Sanket,

We overrode the way weights are loaded in the Faster RCNN class to enable loading weights for individual components separately in order to have more control. Indeed, as you noted, we do not use the standard implementation to load the pretrained model:

https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L16

Instead, we define this function:

https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L23

which sequentially loads the backbone weights using a backbone-customizable load function:

https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L29

the ROI head (only if the number of classes has not changed):

https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L37

and the RPN:

https://github.com/fpv-iplab/stillfast/blob/199ba4902b7a09e4a55c8d3906068d4063bd15a4/stillfast/models/stillfast.py#L47

This approach is more modular, but it should be equivalent to the standard one.

Not sure I got where RPN is loaded twice. Can you point out the two code lines in which that happens? Happy to have a look and fix it if that's the case.

On the results, the "still" branch is basically an object detector. Since images in the lmdb archive are small resolution (I think the short side is 256 pixels), that may be the cause of bad performance (resolution is too low for object detection). Can you please try again with higher resolution images and see if the performance improves?

Best,
Antonino

**Comment by sanketsans** [comment]
Hi Antonio, 
Thanks for the reply and clearing the doubt on the need for customizable load function for Faster-RCNN network. My bad, no the RPN is not loaded twice, I got confused with two implementations. 
I will try with the HR images and let you know. 

Sanket.

**Comment by sanketsans** [comment]
Ok. It works fine with the original image frames for still images.
